In [1]:


import mlflow
# Step 2: Set up the MLflow tracking server
mlflow.set_tracking_uri("http://ec2-16-170-217-141.eu-north-1.compute.amazonaws.com:5000/")

In [7]:
# set or create an experiment
mlflow.set_experiment("exp_5 ml_algo_with_hp_tunning")


<Experiment: artifact_location='s3://my-s3-bucket-of-store-artifact-youtube-data12/mlflow-artifacts/7', creation_time=1764058549473, experiment_id='7', last_update_time=1764058549473, lifecycle_stage='active', name='exp_5 ml_algo_with_hp_tunning', tags={}>

In [8]:
import pandas as pd
df=pd.read_csv('sentiment_clean.csv')

In [9]:
df['sentiment_numeric']=df.pop('sentiment_numeric')

In [5]:
import numpy as np
import pandas as pd
import scipy.sparse as sp
import joblib
import mlflow
import optuna

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, recall_score
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.utils.class_weight import compute_class_weight

import matplotlib.pyplot as plt
import seaborn as sns


# -------------------------
# Target Replace
# -------------------------
df['sentiment_numeric'] = df['sentiment_numeric'].map({-1: 2, 0: 0, 1: 1})


# -------------------------
# Split Numeric + Text
# -------------------------
X_numeric = df.iloc[:, 1:-1]
y = df['sentiment_numeric']

scaler = StandardScaler(with_mean=False)
X_numeric_scaled = scaler.fit_transform(X_numeric)

X_train_num, X_test_num, y_train, y_test, train_idx, test_idx = train_test_split(
    X_numeric_scaled, y, df.index,
    test_size=0.20, random_state=42, stratify=y
)

tfidf = TfidfVectorizer(ngram_range=(1,3), max_features=20000)
X_train_text = tfidf.fit_transform(df.loc[train_idx, 'text_clean'])
X_test_text = tfidf.transform(df.loc[test_idx, 'text_clean'])

X_train = sp.hstack([X_train_text, sp.csr_matrix(X_train_num)])
X_test = sp.hstack([X_test_text, sp.csr_matrix(X_test_num)])


# -------------------------
# Class Weights
# -------------------------
class_weights = compute_class_weight('balanced', classes=np.unique(y_train), y=y_train)
weight_dict = {c: w for c, w in zip(np.unique(y_train), class_weights)}
print("Class Weights:", weight_dict)


# -------------------------
# Optuna Tuning
# -------------------------
def objective(trial):
    alpha = trial.suggest_float("alpha", 0.5, 5.0, log=True)

    model = MultinomialNB(alpha=alpha)
    model.fit(X_train, y_train)

    preds = model.predict(X_test)
    return recall_score(y_test, preds, average="macro")


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=10)

best_alpha = study.best_params["alpha"]
print("\nBest Hyperparameters:", study.best_params)


# -------------------------
# Train Final Model
# -------------------------
model = MultinomialNB(alpha=best_alpha)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)


# -------------------------
# Evaluation
# -------------------------
print("\n=================== FINAL RESULTS ===================")
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:\n", cm)


# -------------------------
# MLflow logging
# -------------------------
with mlflow.start_run(run_name="NB_Optuna_Tuned"):
    mlflow.log_param("model", "Naive Bayes")
    mlflow.log_param("alpha", best_alpha)
    mlflow.log_metric("accuracy", accuracy_score(y_test, y_pred))
    mlflow.log_metric("macro_recall", recall_score(y_test, y_pred, average="macro"))

    plt.figure(figsize=(7,5))
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")
    plt.title("Confusion Matrix - Naive Bayes")
    plt.savefig("cm_nb.png")
    mlflow.log_artifact("cm_nb.png")
    plt.close()

    joblib.dump(model, "naive_bayes_optuna.pkl")
    mlflow.log_artifact("naive_bayes_optuna.pkl")

print("\nModel Saved + Logged Successfully! 🚀")


[I 2025-11-29 20:52:09,668] A new study created in memory with name: no-name-04120dc8-e6ab-4017-817b-54877dd9fbb1
[I 2025-11-29 20:52:09,784] Trial 0 finished with value: 0.6823833576165756 and parameters: {'alpha': 0.8170339366939643}. Best is trial 0 with value: 0.6823833576165756.
[I 2025-11-29 20:52:09,806] Trial 1 finished with value: 0.6348600031272107 and parameters: {'alpha': 3.040130986177387}. Best is trial 0 with value: 0.6823833576165756.
[I 2025-11-29 20:52:09,832] Trial 2 finished with value: 0.6626434433739689 and parameters: {'alpha': 1.6965425502202232}. Best is trial 0 with value: 0.6823833576165756.
[I 2025-11-29 20:52:09,864] Trial 3 finished with value: 0.6238434341338845 and parameters: {'alpha': 3.6697261036108575}. Best is trial 0 with value: 0.6823833576165756.


Class Weights: {np.int64(0): np.float64(0.7256444102225644), np.int64(1): np.float64(0.7350641632774342), np.int64(2): np.float64(3.8242512077294686)}


[I 2025-11-29 20:52:09,899] Trial 4 finished with value: 0.6524452544062393 and parameters: {'alpha': 2.2298454825941234}. Best is trial 0 with value: 0.6823833576165756.
[I 2025-11-29 20:52:09,932] Trial 5 finished with value: 0.6778375970556464 and parameters: {'alpha': 1.1227682828341123}. Best is trial 0 with value: 0.6823833576165756.
[I 2025-11-29 20:52:09,968] Trial 6 finished with value: 0.6688695436707733 and parameters: {'alpha': 1.404437897287747}. Best is trial 0 with value: 0.6823833576165756.
[I 2025-11-29 20:52:10,002] Trial 7 finished with value: 0.6491999445273489 and parameters: {'alpha': 2.4358309190930116}. Best is trial 0 with value: 0.6823833576165756.
[I 2025-11-29 20:52:10,043] Trial 8 finished with value: 0.6416649435517838 and parameters: {'alpha': 2.6734206633985784}. Best is trial 0 with value: 0.6823833576165756.
[I 2025-11-29 20:52:10,077] Trial 9 finished with value: 0.6350066521959891 and parameters: {'alpha': 3.069417231111954}. Best is trial 0 with val


Best Hyperparameters: {'alpha': 0.8170339366939643}

=================== FINAL RESULTS ===================
Accuracy: 0.6835084882780922

Classification Report:
               precision    recall  f1-score   support

           0       0.72      0.64      0.68      4546
           1       0.73      0.73      0.73      4488
           2       0.43      0.68      0.53       862

    accuracy                           0.68      9896
   macro avg       0.63      0.68      0.64      9896
weighted avg       0.70      0.68      0.69      9896


Confusion Matrix:
 [[2915 1107  524]
 [ 977 3264  247]
 [ 157  120  585]]
🏃 View run NB_Optuna_Tuned at: http://ec2-16-170-217-141.eu-north-1.compute.amazonaws.com:5000/#/experiments/7/runs/ebfc1f43653c48d99a573ac52c1906e5
🧪 View experiment at: http://ec2-16-170-217-141.eu-north-1.compute.amazonaws.com:5000/#/experiments/7

Model Saved + Logged Successfully! 🚀
