In [1]:


import mlflow
# Step 2: Set up the MLflow tracking server
mlflow.set_tracking_uri("http://ec2-16-170-217-141.eu-north-1.compute.amazonaws.com:5000/")

In [2]:
# set or create an experiment
mlflow.set_experiment("exp_5 ml_algo_with_hp_tunning")


<Experiment: artifact_location='s3://my-s3-bucket-of-store-artifact-youtube-data12/mlflow-artifacts/7', creation_time=1764058549473, experiment_id='7', last_update_time=1764058549473, lifecycle_stage='active', name='exp_5 ml_algo_with_hp_tunning', tags={}>

In [8]:
import pandas as pd

df=pd.read_csv('sentiment_clean.csv')

In [9]:
df['sentiment_numeric']=df.pop('sentiment_numeric')
df.head()

,text_clean,word_count,num_stop_words,num_chars,num_punctuation_chars,category_gaming,category_movies,category_music,category_technology,hour,...,anger,anticipation,trust,surprise,positive,negative,sadness,disgust,joy,sentiment_numeric
0,all products can be found on since i review 5...,24,9,116,1,0.0,0.0,0.0,1.0,19,...,0.0,0.0,0.333333,0.0,0.333333,0.0,0.0,0.0,0.333333,1
1,bro how to talk to woman in 6 steps is so rela...,12,5,53,0,0.0,0.0,0.0,1.0,23,...,0.0,0.0,0.000000,0.0,1.000000,0.0,0.0,0.0,0.000000,0
2,i was gonna say does it give you the drinks fo...,12,7,54,1,0.0,0.0,0.0,1.0,16,...,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0
3,anyone gonna talk abt what was o. his pc,9,3,40,1,0.0,0.0,0.0,1.0,22,...,0.0,0.0,0.000000,0.0,1.000000,0.0,0.0,0.0,0.000000,0
4,how is everyone not talking about his search?!...,15,6,85,4,0.0,0.0,0.0,1.0,12,...,0.0,0.0,0.000000,0.0,0.500000,0.0,0.0,0.0,0.500000,-1


In [10]:
df[df['sentiment_numeric'].isna()]

,text_clean,word_count,num_stop_words,num_chars,num_punctuation_chars,category_gaming,category_movies,category_music,category_technology,hour,...,anger,anticipation,trust,surprise,positive,negative,sadness,disgust,joy,sentiment_numeric


In [11]:
df[df['text_clean'].isna()]

,text_clean,word_count,num_stop_words,num_chars,num_punctuation_chars,category_gaming,category_movies,category_music,category_technology,hour,...,anger,anticipation,trust,surprise,positive,negative,sadness,disgust,joy,sentiment_numeric


In [ ]:
import numpy as np
import pandas as pd
import scipy.sparse as sp
import matplotlib.pyplot as plt
import seaborn as sns
import joblib
import mlflow
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.utils.class_weight import compute_class_weight
from xgboost import XGBClassifier
import optuna
from sklearn.metrics import recall_score


# -------------------------
# Step 1: Clean target
# -------------------------
df['sentiment_numeric'] = df['sentiment_numeric'].map({-1: 2, 0: 0, 1: 1})

# -------------------------
# Step 2: Numeric features
# -------------------------
X_numeric = df.iloc[:, 1:-1]
y = df['sentiment_numeric']

scaler = StandardScaler()
X_numeric_scaled = scaler.fit_transform(X_numeric)

X_train_num, X_test_num, y_train, y_test, train_idx, test_idx = train_test_split(
    X_numeric_scaled, y, df.index, test_size=0.20, random_state=42, stratify=y
)

# -------------------------
# Step 3: TF-IDF Text
# -------------------------
tfidf = TfidfVectorizer(ngram_range=(1,3), max_features=20000)
X_train_text = tfidf.fit_transform(df.loc[train_idx, 'text_clean'])
X_test_text = tfidf.transform(df.loc[test_idx, 'text_clean'])

X_train = sp.hstack([X_train_text, sp.csr_matrix(X_train_num)])
X_test = sp.hstack([X_test_text, sp.csr_matrix(X_test_num)])

# -------------------------
# Step 4: CLASS-WEIGHTS ONLY
# -------------------------
class_weights = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(y_train),
    y=y_train
)

class_weight_dict = {cls: weight for cls, weight in zip(np.unique(y_train), class_weights)}

sample_weights = np.array([class_weight_dict[label] for label in y_train])

print("Class Weights:", class_weight_dict)

# -------------------------
# Step 5: Optuna Objective
# -------------------------
def objective(trial):

    params = {
        "n_estimators": trial.suggest_int("n_estimators", 100, 400),
        "max_depth": trial.suggest_int("max_depth", 3, 15),
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.3, log=True),
        "subsample": trial.suggest_float("subsample", 0.6, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.6, 1.0),
        "gamma": trial.suggest_float("gamma", 0, 5),
        "min_child_weight": trial.suggest_int("min_child_weight", 1, 10),
        "reg_alpha": trial.suggest_float("reg_alpha", 0.0, 1.0),
        "reg_lambda": trial.suggest_float("reg_lambda", 0.5, 2.0),
        "objective": "multi:softmax",
        "num_class": len(np.unique(y)),
        "random_state": 42,
        "n_jobs": -1
    }

    model = XGBClassifier(**params)
    model.fit(X_train, y_train, sample_weight=sample_weights)

    preds = model.predict(X_test)
    return accuracy_score(y_test, preds)


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=20)

best_params = study.best_params
best_model = XGBClassifier(**best_params)

# -------------------------
# FINAL TRAINING WITH CLASS-WEIGHT
# -------------------------
best_model.fit(X_train, y_train, sample_weight=sample_weights)

y_pred = best_model.predict(X_test)

# -------------------------
# Step 6: MLflow Logging
# -------------------------
with mlflow.start_run(run_name="XGBoost_TFIDF_ClassWeight_NoOversampling"):

    mlflow.log_param("algorithm", "XGBoost")
    mlflow.log_params(best_params)
    mlflow.log_param("vectorizer_type", "TF-IDF")
    mlflow.log_param("imbalance_method", "ClassWeight Only")
    mlflow.log_param("ngram_range", "(1,3)")
    mlflow.log_param("max_features", 20000)

    mlflow.log_metric("accuracy", accuracy_score(y_test, y_pred))

    report = classification_report(y_test, y_pred, output_dict=True)
    for cls, metrics in report.items():
        if isinstance(metrics, dict):
            for metric, value in metrics.items():
                mlflow.log_metric(f"{cls}_{metric}", value)

    cm = confusion_matrix(y_test, y_pred)
    plt.figure(figsize=(8, 6))
    sns.heatmap(cm, annot=True, cmap="Blues", fmt="d")
    plt.title("Confusion Matrix - XGBoost (ClassWeight Only)")
    plt.savefig("confusion_matrix_classweight_only.png")
    mlflow.log_artifact("confusion_matrix_classweight_only.png")
    plt.close()

    model_path = "xgboost_best_classweight_only.pkl"
    joblib.dump(best_model, model_path)
    mlflow.log_artifact(model_path)

print(" Final Model Training COMPLETED — Class-Weight Only")

# -------------------------
# EXACT PRINT OUTPUT YOU WANT
# -------------------------
print("\n=================== FINAL RESULTS ===================")
print(classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n")
print(confusion_matrix(y_test, y_pred))


[I 2025-11-29 14:36:44,326] A new study created in memory with name: no-name-82b6ec79-8382-4de6-bb8f-cac06b77f18c


Class Weights: {np.int64(0): np.float64(0.7256444102225644), np.int64(1): np.float64(0.7350641632774342), np.int64(2): np.float64(3.8242512077294686)}


[I 2025-11-29 14:37:54,572] Trial 0 finished with value: 0.6560226354082458 and parameters: {'n_estimators': 159, 'max_depth': 5, 'learning_rate': 0.015380992646665306, 'subsample': 0.9693120155196091, 'colsample_bytree': 0.7619627060706626, 'gamma': 3.2681888781577757, 'min_child_weight': 6, 'reg_alpha': 0.823160937922745, 'reg_lambda': 1.7948484739393988}. Best is trial 0 with value: 0.6560226354082458.
[I 2025-11-29 14:39:55,524] Trial 1 finished with value: 0.7029102667744543 and parameters: {'n_estimators': 151, 'max_depth': 11, 'learning_rate': 0.09860386600096864, 'subsample': 0.992073614488988, 'colsample_bytree': 0.7404503144782036, 'gamma': 2.7565291125899947, 'min_child_weight': 3, 'reg_alpha': 0.5751807110292658, 'reg_lambda': 0.8789766109331123}. Best is trial 1 with value: 0.7029102667744543.
[I 2025-11-29 14:44:27,859] Trial 2 finished with value: 0.6934114793856103 and parameters: {'n_estimators': 275, 'max_depth': 14, 'learning_rate': 0.02098457158101761, 'subsample': 

🏃 View run XGBoost_TFIDF_ClassWeight_NoOversampling at: http://ec2-16-170-217-141.eu-north-1.compute.amazonaws.com:5000/#/experiments/7/runs/bda2b249130546b9b6b523312ccea481
🧪 View experiment at: http://ec2-16-170-217-141.eu-north-1.compute.amazonaws.com:5000/#/experiments/7
 Final Model Training COMPLETED — Class-Weight Only

=================== FINAL RESULTS ===================
              precision    recall  f1-score   support

           0       0.70      0.75      0.73      4546
           1       0.80      0.68      0.74      4488
           2       0.52      0.72      0.60       862

    accuracy                           0.72      9896
   macro avg       0.67      0.72      0.69      9896
weighted avg       0.73      0.72      0.72      9896


Confusion Matrix:

[[3425  690  431]
 [1268 3070  150]
 [ 170   71  621]]
