In [1]:


import mlflow
# Step 2: Set up the MLflow tracking server
mlflow.set_tracking_uri("http://ec2-16-170-217-141.eu-north-1.compute.amazonaws.com:5000/")

In [2]:
# set or create an experiment
mlflow.set_experiment("exp_5 ml_algo_with_hp_tunning")


<Experiment: artifact_location='s3://my-s3-bucket-of-store-artifact-youtube-data12/mlflow-artifacts/7', creation_time=1764058549473, experiment_id='7', last_update_time=1764058549473, lifecycle_stage='active', name='exp_5 ml_algo_with_hp_tunning', tags={}>

In [3]:
import pandas as pd
df=pd.read_csv('sentiment_clean.csv')

In [5]:
df['sentiment_numeric']=df.pop('sentiment_numeric')

In [8]:
df[df['text_clean'].isna()]

,text_clean,word_count,num_stop_words,num_chars,num_punctuation_chars,category_gaming,category_movies,category_music,category_technology,hour,...,anger,anticipation,trust,surprise,positive,negative,sadness,disgust,joy,sentiment_numeric


In [9]:
import numpy as np
import pandas as pd
import scipy.sparse as sp
import matplotlib.pyplot as plt
import seaborn as sns
import joblib
import mlflow
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, recall_score
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.utils.class_weight import compute_class_weight
from sklearn.ensemble import RandomForestClassifier
import optuna

# -------------------------
# Target Fix
# -------------------------
df['sentiment_numeric'] = df['sentiment_numeric'].map({-1: 2, 0: 0, 1: 1})
df = df.dropna(subset=['sentiment_numeric'])

# -------------------------
# Numeric Features
# -------------------------
X_numeric = df.iloc[:, 1:-1]
y = df['sentiment_numeric']

scaler = StandardScaler()
X_numeric_scaled = scaler.fit_transform(X_numeric)

X_train_num, X_test_num, y_train, y_test, train_idx, test_idx = train_test_split(
    X_numeric_scaled, y, df.index,
    test_size=0.20, random_state=42, stratify=y
)

# -------------------------
# Text TF-IDF
# -------------------------
tfidf = TfidfVectorizer(ngram_range=(1, 3), max_features=20000)
X_train_text = tfidf.fit_transform(df.loc[train_idx, 'text_clean'])
X_test_text = tfidf.transform(df.loc[test_idx, 'text_clean'])

X_train = sp.hstack([X_train_text, sp.csr_matrix(X_train_num)])
X_test = sp.hstack([X_test_text, sp.csr_matrix(X_test_num)])

# -------------------------
# Class Weights
# -------------------------
class_weights = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(y_train),
    y=y_train
)

class_weight_dict = {cls: weight for cls, weight in zip(np.unique(y_train), class_weights)}
print("Class Weights:", class_weight_dict)

# -------------------------
# Optuna Objective
# -------------------------
def objective(trial):
    params = {
        "n_estimators": trial.suggest_int("n_estimators", 200, 800),
        "max_depth": trial.suggest_int("max_depth", 10, 50),
        "min_samples_split": trial.suggest_int("min_samples_split", 2, 10),
        "min_samples_leaf": trial.suggest_int("min_samples_leaf", 1, 5),
        "max_features": trial.suggest_categorical("max_features", ["sqrt", "log2", 0.3, 0.5, 0.7]),
        "class_weight": class_weight_dict,
        "n_jobs": -1
    }

    model = RandomForestClassifier(**params)
    model.fit(X_train, y_train)

    preds = model.predict(X_test)
    return recall_score(y_test, preds, average="macro")


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=15)

best_params = study.best_params
best_params["class_weight"] = class_weight_dict
best_params["n_jobs"] = -1

print("Best Params:", best_params)

# -------------------------
# FINAL MODEL
# -------------------------
best_model = RandomForestClassifier(**best_params)
best_model.fit(X_train, y_train)
y_pred = best_model.predict(X_test)

print("\n=================== FINAL RESULTS ===================")
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Macro Recall:", recall_score(y_test, y_pred, average="macro"))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:\n", cm)

# -------------------------
# MLflow Logging
# -------------------------
with mlflow.start_run(run_name="RF_TFIDF_ClassWeight_optuna_best"):
    mlflow.log_param("model", "RandomForestClassifier")
    mlflow.log_params(best_params)
    mlflow.log_metric("accuracy", accuracy_score(y_test, y_pred))
    mlflow.log_metric("macro_recall", recall_score(y_test, y_pred, average="macro"))

    report = classification_report(y_test, y_pred, output_dict=True)
    for cls, metrics in report.items():
        if isinstance(metrics, dict):
            for metric, value in metrics.items():
                mlflow.log_metric(f"{cls}_{metric}", value)

    plt.figure(figsize=(8,6))
    sns.heatmap(cm, annot=True, cmap="Blues", fmt="d")
    plt.title("Confusion Matrix - Random Forest")
    plt.savefig("cm_rf.png")
    mlflow.log_artifact("cm_rf.png")
    plt.close()

    joblib.dump(best_model, "rf_model.pkl")
    mlflow.log_artifact("rf_model.pkl")


[I 2025-11-29 17:13:05,770] A new study created in memory with name: no-name-bfed682c-706d-4124-8561-323fe3617a09


Class Weights: {np.int64(0): np.float64(0.7256444102225644), np.int64(1): np.float64(0.7350641632774342), np.int64(2): np.float64(3.8242512077294686)}


[I 2025-11-29 17:23:20,723] Trial 0 finished with value: 0.6793641164042982 and parameters: {'n_estimators': 719, 'max_depth': 17, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 0.7}. Best is trial 0 with value: 0.6793641164042982.
[I 2025-11-29 17:30:55,171] Trial 1 finished with value: 0.6886898633959718 and parameters: {'n_estimators': 293, 'max_depth': 41, 'min_samples_split': 10, 'min_samples_leaf': 4, 'max_features': 0.7}. Best is trial 1 with value: 0.6886898633959718.
[I 2025-11-29 17:31:06,992] Trial 2 finished with value: 0.6958420855169248 and parameters: {'n_estimators': 546, 'max_depth': 31, 'min_samples_split': 9, 'min_samples_leaf': 3, 'max_features': 'sqrt'}. Best is trial 2 with value: 0.6958420855169248.
[I 2025-11-29 17:31:16,598] Trial 3 finished with value: 0.6919818592849943 and parameters: {'n_estimators': 766, 'max_depth': 39, 'min_samples_split': 7, 'min_samples_leaf': 1, 'max_features': 'log2'}. Best is trial 2 with value: 0.6958420855169248.
[

Best Params: {'n_estimators': 782, 'max_depth': 50, 'min_samples_split': 10, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'class_weight': {np.int64(0): np.float64(0.7256444102225644), np.int64(1): np.float64(0.7350641632774342), np.int64(2): np.float64(3.8242512077294686)}, 'n_jobs': -1}

=================== FINAL RESULTS ===================
Accuracy: 0.6759296685529507
Macro Recall: 0.7022347355925526

Classification Report:

              precision    recall  f1-score   support

           0       0.69      0.69      0.69      4546
           1       0.77      0.65      0.70      4488
           2       0.40      0.77      0.53       862

    accuracy                           0.68      9896
   macro avg       0.62      0.70      0.64      9896
weighted avg       0.71      0.68      0.68      9896


Confusion Matrix:
 [[3123  752  671]
 [1274 2899  315]
 [ 103   92  667]]
🏃 View run RF_TFIDF_ClassWeight_optuna_best at: http://ec2-16-170-217-141.eu-north-1.compute.amazonaws.com:5000